import React, { useState, useEffect, useRef } from 'react';
import {
  ChatMessage,
  IngestFileItem,
  GeminiModelChoice,
  TacticalRole,
  GroundingChunk,
} from '../types';
import { ASSETS } from '../data/mockData';
import { DOSSIER_TARGETS } from '../data/dossierTargets';

export interface CopilotViewProps {
  focusedFile?: IngestFileItem | null;
  onClearFileFocus?: () => void;
}

const ROLE_DEFINITIONS: Record<
  TacticalRole,
  {
    title: string;
    badge: string;
    icon: string;
    color: string;
    description: string;
    systemInstruction: string;
  }
> = {
  TACTICAL_OPERATIONS: {
    title: 'Tactical Operations Commander',
    badge: 'MHA OPS',
    icon: 'military_tech',
    color: '#ff9933',
    description: 'Syndicate dismantling, inter-agency coordination, and apprehension strategy',
    systemInstruction:
      'You are the DRISTI Tactical Operations Commander, an elite AI assistant embedded in India\'s Ministry of Home Affairs (MHA) tactical intelligence network. You specialize in syndicate dismantling, cross-border hawala tracking, fugitive apprehension, and operational planning under the Bharatiya Nyaya Sanhita (BNS 2023) and PMLA 2002. Provide precise, actionable, numbered tactical directives.',
  },
  FIU_FINANCIAL_INVESTIGATOR: {
    title: 'FIU-IND Hawala & AML Auditor',
    badge: 'FIU-IND',
    icon: 'account_balance',
    color: '#22c55e',
    description: 'Hawala ledgers, UPI smurfing under ₹50,000 threshold, and PMLA Sec 17 asset freezes',
    systemInstruction:
      'You are the DRISTI FIU-IND Principal Financial Investigator. You specialize in detecting illicit financial flows, UPI smurfing micro-transfers designed to circumvent the ₹50,000 mandatory PAN reporting threshold (Rule 114B), Hawala chit distribution networks, shell entities, and asset freezing under Section 17 of PMLA 2002. Conduct forensic financial analysis with exact figures and legal sections.',
  },
  GEOSPATIAL_RECON: {
    title: 'Geospatial Recon & Maps Specialist',
    badge: 'GOOGLE MAPS LIVE',
    icon: 'explore',
    color: '#38bdf8',
    description: 'Live Google Maps intelligence, NHAI FASTag toll gates, and cell tower triangulation',
    systemInstruction:
      'You are the DRISTI Geospatial Recon & Field Intelligence Specialist. You utilize live Google Maps data, NHAI FASTag toll plaza telemetry, and telecom CDR cell tower triangulations to track suspect movements, pinpoint safehouses, calculate transit times, and map escape corridors across India and international transit hubs. Ground your answers in accurate real-world locations, landmarks, and route corridors.',
  },
  LEGAL_PROSECUTOR_65B: {
    title: 'BSA Sec 65B Prosecution Counsel',
    badge: 'BHARATIYA SAKSHYA',
    icon: 'gavel',
    color: '#a855f7',
    description: 'Bharatiya Sakshya Adhiniyam Sec 65B electronic certificates and court chargesheets',
    systemInstruction:
      'You are the DRISTI Senior Cyber Law Prosecutor specializing in the Bharatiya Sakshya Adhiniyam (BSA 2023) Section 65B electronic evidence certification, hash integrity proofs (SHA-256), chain of custody, and drafting chargesheet annexures admissible before Special PMLA and NIA Courts in New Delhi and Mumbai.',
  },
};

const INITIAL_CONVERSATION: ChatMessage[] = [
  {
    id: 'msg-init-1',
    sender: 'USER',
    timestamp: '18:25:00 IST',
    text: 'Analyze correlations between Vikramaditya Singhania, the Hawala accounts at Chandni Chowk, and the recent ₹142.8 Cr UPI smurfing pattern.',
  },
  {
    id: 'msg-init-2',
    sender: 'ASSISTANT',
    timestamp: '18:25:04 IST',
    modelUsed: 'gemini-3.8-flash',
    text: `Based on automated correlation across **CCTNS FIR #182/2026**, **FIU-IND STR Ledger #FIU-IND-STR-2026-881**, and **Jio 5G CDR dumps**:

1. **Entity Nexus**: Target Vikramaditya Singhania holds indirect beneficial ownership over *Trident Logistics FZE* and *Kavach Tech Solutions*, two shell entities flagged by the Enforcement Directorate (ED).
2. **UPI Smurfing Velocity**: NPCI telemetry identified 42 structured UPI micro-transfers between ₹48,000 - ₹49,500 routed through VPA \`singhania.hawala@ybl\` to intentionally circumvent mandatory PAN reporting on transactions exceeding ₹50,000.
3. **Hawala Aggregation Node**: Funds aggregated in HDFC Escrow (A/C: 50200088192011) and were subsequently routed as cash chits through courier Rajesh Sharma at Kucha Mahajani, Chandni Chowk.
4. **Conclusion**: Shell invoices generated by Kavach Tech served as cover for ₹142.8 Crore in transnational remittances to Dubai and Zurich accounts.`,
    provenanceCitations: [
      {
        evidenceId: 'EVD-IND-902',
        title: 'FIU-IND Suspicious Transaction Ledger - Hawala Routing',
        hash: '4a7b0c3d6e9f2a5b8c1d4e7f0a3b6c9d2e1f9f8e4c7b2a1d0f5e8a3b6c9d2e1f',
        bsaSection: 'BSA 2023 Sec 65B(2)',
      },
      {
        evidenceId: 'EVD-IND-901',
        title: 'State Cyber Cell UFED Extraction - Samsung S24 Ultra',
        hash: '9f8e4c7b2a1d0f5e8a3b6c9d2e1f4a7b0c3d6e9f2a5b8c1d4e7f0a3b6c9d2e1f',
        bsaSection: 'BSA 2023 Sec 65B(4)',
      },
      {
        evidenceId: 'EVD-IND-906',
        title: 'IGI Airport T3 CCTV Facial Biometric Stream (Gate 14B)',
        hash: '7b2a1d0f5e8a3b6c9d2e1f4a7b0c3d6e9f2a5b8c1d4e7f0a3b6c9d2e1f4a7b0c',
        bsaSection: 'BSA 2023 Sec 65B(1)',
      },
    ],
    suggestedActions: [
      'Generate Patiala House Special Court Chargesheet Annexure',
      'Issue Freeze Order on HDFC Escrow A/C under PMLA Sec 17',
      'Trigger Bureau of Immigration Airport Gate Intercept',
    ],
  },
];

export const CopilotView: React.FC<CopilotViewProps> = ({
  focusedFile = null,
  onClearFileFocus,
}) => {
  const [messages, setMessages] = useState<ChatMessage[]>(INITIAL_CONVERSATION);
  const [inputValue, setInputValue] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [activeRole, setActiveRole] = useState<TacticalRole>('TACTICAL_OPERATIONS');
  const [selectedModel, setSelectedModel] = useState<GeminiModelChoice>('gemini-3.8-flash');
  const [enableMapsGrounding, setEnableMapsGrounding] = useState<boolean>(false);
  const [userLocation, setUserLocation] = useState<{ latitude: number; longitude: number }>({
    latitude: 28.6139,
    longitude: 77.209, // New Delhi default coordinates
  });
  const [locationStatus, setLocationStatus] = useState<string>('Delhi NCR Anchor (28.61°N, 77.21°E)');
  const [serverStatus, setServerStatus] = useState<'checking' | 'connected' | 'no-key'>('checking');
  const [apiErrorMessage, setApiErrorMessage] = useState<string | null>(null);

  const chatContainerRef = useRef<HTMLDivElement>(null);

  // Check backend Gemini connectivity
  useEffect(() => {
    fetch('/api/health')
      .then((res) => res.json())
      .then((data) => {
        if (data.hasApiKey) {
          setServerStatus('connected');
        } else {
          setServerStatus('no-key');
        }
      })
      .catch(() => {
        setServerStatus('no-key');
      });
  }, []);

  // Request browser geolocation if available
  const handleRequestLiveLocation = () => {
    if ('geolocation' in navigator) {
      setLocationStatus('Acquiring GPS fix...');
      navigator.geolocation.getCurrentPosition(
        (pos) => {
          const lat = parseFloat(pos.coords.latitude.toFixed(4));
          const lng = parseFloat(pos.coords.longitude.toFixed(4));
          setUserLocation({ latitude: lat, longitude: lng });
          setLocationStatus(`Live GPS (${lat}°N, ${lng}°E)`);
        },
        (err) => {
          console.warn('Geolocation denied or failed:', err);
          setLocationStatus('Delhi NCR Tactical Grid (28.61°N, 77.21°E)');
        },
        { timeout: 8000 }
      );
    }
  };

  // Scroll to bottom when messages update
  useEffect(() => {
    if (chatContainerRef.current) {
      chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight;
    }
  }, [messages, isGenerating]);

  // When focused file changes, notify in chat
  useEffect(() => {
    if (!focusedFile) return;

    const fileNotice: ChatMessage = {
      id: `file-focus-${Date.now()}`,
      sender: 'ASSISTANT',
      timestamp: new Date().toTimeString().substring(0, 8) + ' IST',
      text: `**Active Investigation Target File Loaded: ${focusedFile.name}**
• **Channel / Source**: ${focusedFile.sourceCategory} Telemetry
• **Record Size**: ${focusedFile.size} (${focusedFile.extractedEntities} extracted entities)
• **File Hash**: \`${focusedFile.id.toUpperCase()}-SHA256-VERIFIED\`
• **Scope**: Ready for contextual queries against this specific case package.`,
      modelUsed: 'gemini-3.8-flash',
      suggestedActions: [
        `Correlate ${focusedFile.name} against Primary Target Vikramaditya Singhania`,
        `Extract all UPI VPAs and phone numbers in ${focusedFile.name}`,
        `Verify Section 65B certificate for ${focusedFile.name}`,
      ],
    };
    setMessages((prev) => [...prev, fileNotice]);
  }, [focusedFile?.id]);

  // Automatically enable Maps Grounding when Geospatial Recon role is selected
  useEffect(() => {
    if (activeRole === 'GEOSPATIAL_RECON') {
      setEnableMapsGrounding(true);
      setSelectedModel('gemini-3.5-flash');
    }
  }, [activeRole]);

  const handleSendMessage = async (textToSend?: string) => {
    const queryText = (textToSend || inputValue).trim();
    if (!queryText || isGenerating) return;

    setApiErrorMessage(null);

    const userMsg: ChatMessage = {
      id: `msg-${Date.now()}`,
      sender: 'USER',
      timestamp: new Date().toTimeString().substring(0, 8) + ' IST',
      text: queryText,
    };

    // Append user message immediately
    const updatedMessages = [...messages, userMsg];
    setMessages(updatedMessages);
    if (!textToSend) setInputValue('');
    setIsGenerating(true);

    // Auto-detect if query relates to map/location, auto-enable maps grounding
    const lowerQuery = queryText.toLowerCase();
    const isLocationQuery =
      enableMapsGrounding ||
      lowerQuery.includes('where is') ||
      lowerQuery.includes('location of') ||
      lowerQuery.includes('map') ||
      lowerQuery.includes('toll plaza') ||
      lowerQuery.includes('kherki daula') ||
      lowerQuery.includes('chandni chowk') ||
      lowerQuery.includes('igi airport') ||
      lowerQuery.includes('police station') ||
      lowerQuery.includes('address') ||
      lowerQuery.includes('route');

    const modelToUse: GeminiModelChoice = isLocationQuery
      ? 'gemini-3.5-flash' // Must use gemini-3.5-flash with googleMaps tool as mandated
      : selectedModel;

    // Prepare multi-turn history payload
    // Filter to last 8 turns for high relevance and bounded tokens
    const recentTurns = updatedMessages.slice(-8).map((m) => ({
      role: m.sender === 'USER' ? 'user' : 'model',
      text: m.text,
    }));

    // Inject file scope or role context into system instruction
    let dynamicSystemInstruction = ROLE_DEFINITIONS[activeRole].systemInstruction;
    if (focusedFile) {
      dynamicSystemInstruction += `\n\nCURRENT SCOPED FILE FOCUS: ${focusedFile.name} (${focusedFile.sourceCategory} data). Focus analysis on entities and evidence parsed from this package.`;
    }

    try {
      const response = await fetch('/api/gemini/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: recentTurns,
          systemInstruction: dynamicSystemInstruction,
          model: modelToUse,
          enableMapsGrounding: isLocationQuery,
          userLocation,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || `HTTP ${response.status}: Failed to generate response`);
      }

      const assistantMsg: ChatMessage = {
        id: `msg-${Date.now()}`,
        sender: 'ASSISTANT',
        timestamp: new Date().toTimeString().substring(0, 8) + ' IST',
        text: data.text || 'No response generated.',
        modelUsed: data.modelUsed || modelToUse,
        isMapsGrounded: isLocationQuery,
        groundingChunks: data.groundingChunks || [],
        groundingMetadata: data.groundingMetadata,
        provenanceCitations: [
          {
            evidenceId: 'EVD-BSA-701',
            title: `DRISTI Telemetry Log (${data.modelUsed || modelToUse})`,
            hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
            bsaSection: 'BSA 2023 Sec 65B(2)',
          },
        ],
        suggestedActions: [
          'Add citation to Patiala House Case Docket',
          'Cross-reference against CDR Base Stations',
          'Export Section 65B BSA Affidavit',
        ],
      };

      setMessages((prev) => [...prev, assistantMsg]);
    } catch (err: any) {
      console.error('Failed to query Gemini:', err);
      setApiErrorMessage(err.message || 'Error contacting Gemini service');

      // Provide helpful tactical fallback message in the chat thread
      const errorAssistantMsg: ChatMessage = {
        id: `err-${Date.now()}`,
        sender: 'ASSISTANT',
        timestamp: new Date().toTimeString().substring(0, 8) + ' IST',
        text: `**Intelligence Transmission Alert**: Unable to complete live query via ${modelToUse}.

*Diagnostic Notice*: ${err.message || 'Service unreachable'}.
${
  err.message?.includes('API_KEY')
    ? '\n**Resolution Step**: Please configure a valid `GEMINI_API_KEY` in the **Settings > Secrets** panel in AI Studio.'
    : '\n*Offline Fallback Intelligence*: Correlating query locally across DRISTI CCTNS FIR #182/2026, FIU-IND STR Ledger #881, and NHAI FASTag telemetry for Vikramaditya Singhania.'
}`,
        isError: true,
        modelUsed: 'OFFLINE_FALLBACK',
      };
      setMessages((prev) => [...prev, errorAssistantMsg]);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleClearChat = () => {
    setMessages([
      {
        id: `msg-${Date.now()}`,
        sender: 'ASSISTANT',
        timestamp: new Date().toTimeString().substring(0, 8) + ' IST',
        text: `**DRISTI Tactical Copilot Session Initialized.**
Active Role: **${ROLE_DEFINITIONS[activeRole].title}**
Engine: **${selectedModel}** (Maps Grounding: ${enableMapsGrounding ? 'ACTIVE' : 'READY'})

Awaiting tactical intelligence queries regarding Hawala ledgers, CDR towers, FASTag telemetry, or Section 65B BSA compliance.`,
        modelUsed: selectedModel,
      },
    ]);
  };

  // Helper to extract Google Maps places from groundingChunks
  const extractMapsPlaces = (chunks?: GroundingChunk[]) => {
    if (!chunks || !Array.isArray(chunks)) return [];
    const places: { title: string; uri: string; snippets: string[] }[] = [];

    for (const chunk of chunks) {
      if (chunk.maps?.uri) {
        const snippets: string[] = [];
        if (chunk.maps.placeAnswerSources?.reviewSnippets) {
          for (const s of chunk.maps.placeAnswerSources.reviewSnippets) {
            if (s.content) snippets.push(s.content);
          }
        }
        places.push({
          title: chunk.maps.title || 'Google Maps Location',
          uri: chunk.maps.uri,
          snippets,
        });
      }
    }
    return places;
  };

  // Helper to extract web links from groundingChunks
  const extractWebLinks = (chunks?: GroundingChunk[]) => {
    if (!chunks || !Array.isArray(chunks)) return [];
    return chunks.filter((c) => c.web?.uri).map((c) => c.web!);
  };

  return (
    <div className="space-y-4">
      {/* Active File Focus Notification Banner */}
      {focusedFile && (
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 p-3 bg-[#14234b] border border-[#ff9933]/60 rounded-xl text-xs font-mono shadow-[0_0_15px_rgba(255,153,51,0.15)] animate-fadeIn">
          <div className="flex items-center space-x-2.5">
            <span className="material-symbols-outlined text-lg text-[#ff9933]">filter_alt</span>
            <div>
              <div className="flex items-center space-x-2">
                <span className="text-[#ff9933] font-bold">ACTIVE COPILOT FILE FOCUS:</span>
                <span className="text-[#f8fafc] font-semibold">{focusedFile.name}</span>
                <span className="text-[10px] px-1.5 py-0.2 rounded bg-[#ff9933]/20 text-[#ffb366] border border-[#ff9933]/40">
                  {focusedFile.sourceCategory}
                </span>
              </div>
              <p className="text-[11px] text-[#94a3b8] mt-0.5">
                Gemini Copilot multi-turn reasoning is scoped to parse and correlate entities from this file.
              </p>
            </div>
          </div>
          {onClearFileFocus && (
            <button
              onClick={onClearFileFocus}
              className="px-3 py-1.5 rounded-lg bg-[#0e1938] hover:bg-[#1a2e63] text-[#f8fafc] hover:text-[#ff9933] border border-[#1e305e] transition-all text-xs font-bold shrink-0 cursor-pointer"
            >
              SHOW ALL INGESTED FILES
            </button>
          )}
        </div>
      )}

      {/* Main Header & Model / Role Toolbar */}
      <div className="bg-[#0e1938] border border-[#1e305e] rounded-xl p-4 sm:p-5 shadow-sm space-y-4">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
          <div>
            <div className="flex items-center space-x-2 text-[11px] font-mono text-[#ff9933] uppercase tracking-wider mb-1">
              <span className="material-symbols-outlined text-sm">smart_toy</span>
              <span>GEMINI AI MULTI-TURN COPILOT // TACTICAL INTELLIGENCE</span>
            </div>
            <h2 className="text-lg sm:text-xl font-bold text-[#f8fafc] font-['Space_Grotesk',sans-serif] tracking-wide flex items-center space-x-2">
              <span>DRISTI Gemini Neural Reasoner</span>
              <span className="text-xs px-2 py-0.5 rounded bg-[#ff9933]/20 text-[#ff9933] border border-[#ff9933]/40 font-mono">
                MHA RESTRICTED
              </span>
            </h2>
            <p className="text-xs text-[#94a3b8] mt-0.5 max-w-2xl">
              Multi-turn tactical investigation chat powered by Google Gemini, equipped with Google Maps Grounding, CDR cell-tower triangulations, and Section 65B BSA 2023 evidence provenance.
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            {/* Server Connection Status */}
            <div className="flex items-center space-x-1.5 px-2.5 py-1 rounded-lg border font-mono text-[11px] bg-[#070d1e] border-[#1e305e]">
              <span
                className={`w-2 h-2 rounded-full ${
                  serverStatus === 'connected'
                    ? 'bg-[#22c55e] animate-pulse'
                    : serverStatus === 'no-key'
                    ? 'bg-[#fbbf24]'
                    : 'bg-[#94a3b8]'
                }`}
              ></span>
              <span className={serverStatus === 'connected' ? 'text-[#22c55e]' : 'text-[#fbbf24]'}>
                {serverStatus === 'connected'
                  ? 'GEMINI LIVE'
                  : serverStatus === 'no-key'
                  ? 'API KEY REQ (SETTINGS)'
                  : 'CONNECTING'}
              </span>
            </div>

            {/* Clear Chat Button */}
            <button
              onClick={handleClearChat}
              className="px-2.5 py-1 rounded-lg bg-[#070d1e] hover:bg-[#14234b] text-[#94a3b8] hover:text-[#f8fafc] border border-[#1e305e] transition-colors font-mono text-xs flex items-center space-x-1 cursor-pointer"
              title="Reset conversation thread"
            >
              <span className="material-symbols-outlined text-sm">restart_alt</span>
              <span>RESET THREAD</span>
            </button>
          </div>
        </div>

        {/* Tactical Role & Model Controls Grid */}
        <div className="grid grid-cols-1 md:grid-cols-12 gap-3 pt-3 border-t border-[#1e305e]/80">
          {/* Role Selection */}
          <div className="md:col-span-6 space-y-1.5">
            <label className="text-[10px] font-mono text-[#94a3b8] uppercase font-bold flex items-center space-x-1">
              <span className="material-symbols-outlined text-xs text-[#ff9933]">badge</span>
              <span>ASSISTANT TACTICAL ROLE &amp; SYSTEM INSTRUCTION:</span>
            </label>
            <div className="grid grid-cols-2 gap-1.5">
              {(Object.keys(ROLE_DEFINITIONS) as TacticalRole[]).map((r) => {
                const roleDef = ROLE_DEFINITIONS[r];
                const isSelected = activeRole === r;
                return (
                  <button
                    key={r}
                    onClick={() => setActiveRole(r)}
                    className={`flex items-center space-x-1.5 p-2 rounded-lg border text-left font-mono transition-all cursor-pointer ${
                      isSelected
                        ? 'bg-[#ff9933]/20 border-[#ff9933] text-[#f8fafc] shadow-[0_0_10px_rgba(255,153,51,0.2)]'
                        : 'bg-[#070d1e] border-[#1e305e] text-[#94a3b8] hover:text-[#f8fafc] hover:border-[#1e305e]/80'
                    }`}
                  >
                    <span
                      className="material-symbols-outlined text-sm shrink-0"
                      style={{ color: isSelected ? '#ff9933' : '#94a3b8' }}
                    >
                      {roleDef.icon}
                    </span>
                    <div className="truncate">
                      <div className="text-[11px] font-bold truncate">{roleDef.title}</div>
                      <div className="text-[9px] opacity-75 truncate">{roleDef.badge}</div>
                    </div>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Model Selection */}
          <div className="md:col-span-3 space-y-1.5">
            <label className="text-[10px] font-mono text-[#94a3b8] uppercase font-bold flex items-center space-x-1">
              <span className="material-symbols-outlined text-xs text-[#38bdf8]">psychology</span>
              <span>GEMINI MODEL ENGINE:</span>
            </label>
            <select
              value={selectedModel}
              onChange={(e) => setSelectedModel(e.target.value as GeminiModelChoice)}
              className="w-full bg-[#070d1e] text-[#f8fafc] text-xs font-mono border border-[#1e305e] rounded-lg p-2 focus:outline-none focus:border-[#ff9933] cursor-pointer"
            >
              <option value="gemini-3.8-flash">gemini-3.8-flash (Default // Balanced Intelligence)</option>
              <option value="gemini-3.5-flash">gemini-3.5-flash (General Tasks &amp; Maps Grounding)</option>
              <option value="gemini-3.1-flash-lite">gemini-3.1-flash-lite (Ultra-Fast Telemetry Lookup)</option>
              <option value="gemini-3.1-pro-preview">gemini-3.1-pro-preview (Deep Forensic Reasoning)</option>
            </select>
            <div className="text-[10px] font-mono text-[#94a3b8] flex items-center space-x-1">
              <span className="material-symbols-outlined text-xs text-[#22c55e]">check_circle</span>
              <span>
                {selectedModel === 'gemini-3.8-flash'
                  ? 'Primary model for high-throughput case investigation'
                  : selectedModel === 'gemini-3.5-flash'
                  ? 'Required for live Google Maps tool grounding'
                  : selectedModel === 'gemini-3.1-flash-lite'
                  ? 'Low-latency queries for rapid field response'
                  : 'Deep multi-hop chain-of-custody analysis'}
              </span>
            </div>
          </div>

          {/* Google Maps Grounding Live Toggle */}
          <div className="md:col-span-3 space-y-1.5">
            <label className="text-[10px] font-mono text-[#94a3b8] uppercase font-bold flex items-center space-x-1">
              <span className="material-symbols-outlined text-xs text-[#22c55e]">pin_drop</span>
              <span>MAPS GROUNDING TOOL:</span>
            </label>
            <button
              onClick={() => {
                const next = !enableMapsGrounding;
                setEnableMapsGrounding(next);
                if (next) setSelectedModel('gemini-3.5-flash');
              }}
              className={`w-full flex items-center justify-between p-2 rounded-lg border font-mono text-xs transition-all cursor-pointer ${
                enableMapsGrounding
                  ? 'bg-[#14234b] border-[#22c55e] text-[#22c55e] shadow-[0_0_12px_rgba(34,197,94,0.25)]'
                  : 'bg-[#070d1e] border-[#1e305e] text-[#94a3b8] hover:text-[#f8fafc]'
              }`}
            >
              <div className="flex items-center space-x-2">
                <span className="material-symbols-outlined text-base">
                  {enableMapsGrounding ? 'explore' : 'explore_off'}
                </span>
                <span className="font-bold">
                  {enableMapsGrounding ? 'MAPS LIVE ACTIVE' : 'MAPS GROUNDING OFF'}
                </span>
              </div>
              <span
                className={`text-[9px] px-1.5 py-0.5 rounded font-bold ${
                  enableMapsGrounding ? 'bg-[#22c55e]/20 text-[#22c55e]' : 'bg-[#1e305e] text-[#94a3b8]'
                }`}
              >
                {enableMapsGrounding ? 'gemini-3.5-flash' : 'STANDBY'}
              </span>
            </button>
            <div className="flex items-center justify-between text-[10px] font-mono text-[#94a3b8]">
              <span className="truncate">{locationStatus}</span>
              <button
                onClick={handleRequestLiveLocation}
                className="text-[#38bdf8] hover:underline cursor-pointer shrink-0 ml-1"
                title="Get device GPS location"
              >
                [GET GPS]
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Dual-Pane Layout: Left Context & Right Multi-Turn Chat */}
      <div className="grid grid-cols-1 xl:grid-cols-12 gap-5">
        {/* Left Pane: Case Targets & Preset Operations */}
        <div className="xl:col-span-4 space-y-4">
          {/* Target Selection Card */}
          <div className="bg-[#0e1938] border border-[#1e305e] rounded-xl p-4 shadow-sm space-y-3 font-mono">
            <div className="flex items-center justify-between border-b border-[#1e305e] pb-2.5">
              <div className="flex items-center space-x-2 text-xs text-[#ff9933] font-bold">
                <span className="material-symbols-outlined text-sm">supervised_user_circle</span>
                <span>SYNDICATE TARGET DOSSIERS</span>
              </div>
              <span className="text-[10px] text-[#22c55e] bg-[#138808]/20 px-2 py-0.5 rounded border border-[#138808]/40">
                4 TARGETS
              </span>
            </div>

            <div className="space-y-2">
              {DOSSIER_TARGETS.map((target) => (
                <div
                  key={target.id}
                  onClick={() =>
                    handleSendMessage(
                      `Provide comprehensive dossier analysis on target ${target.name} (${target.syndicateRole}), including active FIRs, warrants, and FIU account balances.`
                    )
                  }
                  className="p-2.5 bg-[#070d1e] hover:bg-[#14234b] rounded-lg border border-[#1e305e] hover:border-[#ff9933]/60 transition-all cursor-pointer flex items-center space-x-3 group"
                >
                  <div className="w-10 h-10 rounded overflow-hidden border border-[#1e305e] group-hover:border-[#ff9933] shrink-0 bg-[#0e1938]">
                    <img
                      src={target.mugshotUrl}
                      alt={target.name}
                      className="w-full h-full object-cover"
                      referrerPolicy="no-referrer"
                    />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-bold text-[#f8fafc] truncate group-hover:text-[#ff9933] font-sans">
                        {target.name}
                      </span>
                      <span className="text-[9px] px-1 rounded bg-[#ef4444]/20 text-[#ef4444] border border-[#ef4444]/40 font-bold">
                        {target.threatScore}
                      </span>
                    </div>
                    <div className="text-[10px] text-[#ffb366] truncate">{target.syndicateRole}</div>
                    <div className="text-[9px] text-[#94a3b8] truncate">{target.firRef}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Preset Tactical & Google Maps Prompts */}
          <div className="bg-[#0e1938] border border-[#1e305e] rounded-xl p-4 shadow-sm space-y-3 font-mono">
            <div className="flex items-center justify-between border-b border-[#1e305e] pb-2">
              <span className="text-xs text-[#38bdf8] font-bold flex items-center space-x-1.5">
                <span className="material-symbols-outlined text-sm">explore</span>
                <span>GOOGLE MAPS &amp; GROUNDED QUERIES:</span>
              </span>
              <span className="text-[9px] text-[#38bdf8] bg-[#38bdf8]/10 px-1.5 py-0.5 rounded border border-[#38bdf8]/30">
                LIVE
              </span>
            </div>

            <div className="space-y-1.5 text-[11px]">
              {[
                {
                  label: 'Locate Chandni Chowk Hawala hubs & nearest Delhi Police chowkis on Google Maps',
                  maps: true,
                },
                {
                  label: 'Verify Kherki Daula Toll Plaza on NH-48 and FASTag sensor corridor via Google Maps',
                  maps: true,
                },
                {
                  label: 'Pinpoint IGI Airport Terminal 3 VIP departure lanes and immigration control points',
                  maps: true,
                },
                {
                  label: 'Correlate Reliance Jio CDR cell tower coordinates with suspect hideouts',
                  maps: true,
                },
                {
                  label: 'Draft Section 65B BSA electronic evidence certificate for Samsung S24 extraction',
                  maps: false,
                },
              ].map((item, i) => (
                <button
                  key={i}
                  onClick={() => {
                    if (item.maps) {
                      setEnableMapsGrounding(true);
                      setSelectedModel('gemini-3.5-flash');
                    }
                    handleSendMessage(item.label);
                  }}
                  className="w-full text-left p-2 rounded-lg bg-[#070d1e] hover:bg-[#14234b] text-[#cbd5e1] hover:text-[#ff9933] border border-[#1e305e] hover:border-[#ff9933]/50 transition-all cursor-pointer flex items-start space-x-1.5"
                >
                  <span className="text-[#ff9933] mt-0.5 shrink-0">➔</span>
                  <span className="leading-tight">{item.label}</span>
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Right Pane: Interactive Conversational Workspace */}
        <div className="xl:col-span-8 bg-[#0e1938] border border-[#1e305e] rounded-xl p-4 shadow-sm flex flex-col h-[650px]">
          {/* Conversation Thread Header */}
          <div className="flex items-center justify-between border-b border-[#1e305e] pb-2.5 mb-3 font-mono text-xs">
            <div className="flex items-center space-x-2">
              <span className="w-2 h-2 rounded-full bg-[#ff9933] animate-ping"></span>
              <span className="text-[#f8fafc] font-bold">SECURE THREAD // CASE RECORD #OP-TRIDENT-2026</span>
            </div>
            <div className="flex items-center space-x-3 text-[11px] text-[#94a3b8]">
              <span>ROLE: <strong className="text-[#ff9933]">{ROLE_DEFINITIONS[activeRole].badge}</strong></span>
              <span>•</span>
              <span>ENGINE: <strong className="text-[#38bdf8]">{selectedModel}</strong></span>
              <span>•</span>
              <span className={enableMapsGrounding ? 'text-[#22c55e] font-bold' : 'text-[#94a3b8]'}>
                MAPS: {enableMapsGrounding ? 'ACTIVE' : 'OFF'}
              </span>
            </div>
          </div>

          {/* API Error Notification if present */}
          {apiErrorMessage && (
            <div className="mb-3 p-2.5 bg-[#ef4444]/15 border border-[#ef4444]/40 rounded-lg text-xs font-mono text-[#f87171] flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <span className="material-symbols-outlined text-base">warning</span>
                <span>{apiErrorMessage}</span>
              </div>
              <button
                onClick={() => setApiErrorMessage(null)}
                className="text-xs hover:text-white cursor-pointer px-1"
              >
                ✕
              </button>
            </div>
          )}

          {/* Scrollable Message Thread */}
          <div
            ref={chatContainerRef}
            className="flex-1 overflow-y-auto space-y-4 pr-2 font-mono text-xs scroll-smooth"
          >
            {messages.map((msg) => {
              const mapsPlaces = extractMapsPlaces(msg.groundingChunks);
              const webLinks = extractWebLinks(msg.groundingChunks);

              return (
                <div
                  key={msg.id}
                  className={`p-4 rounded-xl border transition-all ${
                    msg.sender === 'USER'
                      ? 'bg-[#ff9933]/15 border-[#ff9933]/50 text-[#f8fafc] ml-8 sm:ml-16 shadow-sm'
                      : msg.isError
                      ? 'bg-[#450a0a]/30 border-[#ef4444]/40 text-[#fca5a5] mr-8 sm:mr-16'
                      : 'bg-[#070d1e] border-[#1e305e] text-[#f8fafc] mr-8 sm:mr-16 shadow-sm'
                  }`}
                >
                  {/* Message Header */}
                  <div className="flex items-center justify-between border-b border-[#1e305e]/80 pb-2 mb-2.5">
                    <span
                      className={`font-bold flex items-center space-x-1.5 text-xs ${
                        msg.sender === 'USER'
                          ? 'text-[#ff9933]'
                          : msg.isError
                          ? 'text-[#ef4444]'
                          : 'text-[#22c55e]'
                      }`}
                    >
                      <span className="material-symbols-outlined text-sm">
                        {msg.sender === 'USER'
                          ? 'person'
                          : msg.isError
                          ? 'error'
                          : 'smart_toy'}
                      </span>
                      <span>
                        {msg.sender === 'USER'
                          ? 'INVESTIGATING OFFICER (ACP RAO)'
                          : `DRISTI COPILOT [${msg.modelUsed || selectedModel}]`}
                      </span>
                    </span>
                    <div className="flex items-center space-x-2 text-[10px] text-[#94a3b8]">
                      {msg.isMapsGrounded && (
                        <span className="flex items-center space-x-0.5 text-[#22c55e] bg-[#22c55e]/10 px-1.5 py-0.2 rounded border border-[#22c55e]/30">
                          <span className="material-symbols-outlined text-xs">pin_drop</span>
                          <span>MAPS GROUNDED</span>
                        </span>
                      )}
                      <span>{msg.timestamp}</span>
                    </div>
                  </div>

                  {/* Message Body with Markdown formatting support */}
                  <div className="whitespace-pre-wrap leading-relaxed font-sans text-xs sm:text-[13px] text-[#cbd5e1] space-y-2">
                    {msg.text}
                  </div>

                  {/* Google Maps Grounded Places Section (Mandatory display of extracted place URLs & review snippets) */}
                  {mapsPlaces.length > 0 && (
                    <div className="mt-3 pt-3 border-t border-[#1e305e] space-y-2">
                      <div className="flex items-center justify-between text-[11px] font-mono text-[#22c55e] font-bold">
                        <span className="flex items-center space-x-1">
                          <span className="material-symbols-outlined text-sm">map</span>
                          <span>GOOGLE MAPS GROUNDED PLACES &amp; TELEMETRY ({mapsPlaces.length}):</span>
                        </span>
                        <span className="text-[10px] text-[#94a3b8]">LIVE RETRIEVAL</span>
                      </div>

                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                        {mapsPlaces.map((place, pIdx) => (
                          <div
                            key={pIdx}
                            className="p-2.5 rounded-lg bg-[#0e1938] border border-[#22c55e]/40 space-y-1.5 font-mono text-xs"
                          >
                            <div className="flex items-start justify-between gap-1">
                              <span className="font-bold text-[#f8fafc] flex items-center space-x-1 font-sans text-xs">
                                <span className="material-symbols-outlined text-xs text-[#22c55e]">place</span>
                                <span>{place.title}</span>
                              </span>
                              <a
                                href={place.uri}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="px-2 py-0.5 rounded bg-[#22c55e]/20 hover:bg-[#22c55e] text-[#22c55e] hover:text-[#070d1e] font-bold text-[10px] transition-colors shrink-0 inline-flex items-center space-x-0.5 cursor-pointer"
                              >
                                <span>OPEN MAPS</span>
                                <span className="material-symbols-outlined text-xs">open_in_new</span>
                              </a>
                            </div>

                            {/* Review Snippets from Maps Answer Sources */}
                            {place.snippets.length > 0 && (
                              <div className="space-y-1 pt-1 border-t border-[#1e305e]/80">
                                {place.snippets.map((snip, sIdx) => (
                                  <p
                                    key={sIdx}
                                    className="text-[10px] text-[#94a3b8] italic font-sans bg-[#070d1e] p-1 rounded"
                                  >
                                    "{snip}"
                                  </p>
                                ))}
                              </div>
                            )}
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Web Grounding Links */}
                  {webLinks.length > 0 && mapsPlaces.length === 0 && (
                    <div className="mt-3 pt-2.5 border-t border-[#1e305e] space-y-1">
                      <span className="text-[10px] font-mono text-[#38bdf8] uppercase block font-bold">
                        Grounding Sources:
                      </span>
                      <div className="flex flex-wrap gap-1.5">
                        {webLinks.map((wl, wIdx) => (
                          <a
                            key={wIdx}
                            href={wl.uri}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-[10px] px-2 py-0.5 rounded bg-[#14234b] hover:bg-[#1a2e63] text-[#38bdf8] border border-[#1e305e] inline-flex items-center space-x-1 cursor-pointer"
                          >
                            <span className="truncate max-w-[200px]">{wl.title || wl.uri}</span>
                            <span className="material-symbols-outlined text-xs">open_in_new</span>
                          </a>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Provenance Citations */}
                  {msg.provenanceCitations && msg.provenanceCitations.length > 0 && (
                    <div className="mt-3 pt-2.5 border-t border-[#1e305e] space-y-1.5">
                      <span className="text-[10px] font-mono text-[#ff9933] uppercase block font-bold">
                        Evidentiary Provenance Citations (Section 65B BSA 2023):
                      </span>
                      {msg.provenanceCitations.map((cit) => (
                        <div
                          key={cit.evidenceId}
                          className="p-2 bg-[#0e1938] rounded-lg border border-[#1e305e] font-mono text-[10px]"
                        >
                          <div className="flex justify-between text-[#f8fafc]">
                            <span className="text-[#ff9933] font-bold">{cit.evidenceId}</span>
                            <span className="text-[#22c55e]">{cit.bsaSection || 'BSA SEC 65B CERTIFIED'}</span>
                          </div>
                          <div className="text-[#94a3b8] truncate">{cit.title}</div>
                          <div className="text-[#38bdf8] truncate mt-0.5 font-mono select-all">
                            SHA-256: {cit.hash}
                          </div>
                        </div>
                      ))}
                    </div>
                  )}

                  {/* Suggested Next Actions */}
                  {msg.suggestedActions && msg.suggestedActions.length > 0 && (
                    <div className="mt-3 pt-2 border-t border-[#1e305e]/60 flex flex-wrap gap-1.5">
                      {msg.suggestedActions.map((action, aIdx) => (
                        <button
                          key={aIdx}
                          onClick={() => handleSendMessage(action)}
                          className="text-[10px] font-mono px-2 py-1 rounded bg-[#0e1938] hover:bg-[#14234b] text-[#cbd5e1] hover:text-[#ff9933] border border-[#1e305e] transition-colors cursor-pointer"
                        >
                          ➔ {action}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              );
            })}

            {isGenerating && (
              <div className="p-4 rounded-xl bg-[#070d1e] border border-[#ff9933]/50 mr-8 sm:mr-16 text-xs font-mono text-[#ff9933] flex items-center space-x-3 animate-pulse">
                <span className="material-symbols-outlined animate-spin text-base">rotate_right</span>
                <div>
                  <div className="font-bold">
                    Querying Gemini ({enableMapsGrounding ? 'gemini-3.5-flash with Google Maps Grounding' : selectedModel})...
                  </div>
                  <div className="text-[10px] text-[#94a3b8] mt-0.5">
                    Synthesizing multi-agency case telemetry, CCTNS registries, and live geographic coordinates...
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Interactive Chat Input Bar */}
          <div className="mt-3 pt-3 border-t border-[#1e305e]">
            <form
              onSubmit={(e) => {
                e.preventDefault();
                handleSendMessage();
              }}
              className="flex items-center space-x-2"
            >
              <div className="relative flex-1">
                <input
                  type="text"
                  placeholder={
                    enableMapsGrounding
                      ? "Ask Gemini with Google Maps Grounding (e.g., 'Locate Chandni Chowk Hawala couriers and nearby police chowkis')..."
                      : "Query DRISTI Gemini Copilot on Hawala structuring, CDR towers, or BSA 65B evidence..."
                  }
                  value={inputValue}
                  onChange={(e) => setInputValue(e.target.value)}
                  disabled={isGenerating}
                  className="w-full bg-[#070d1e] text-xs font-mono text-[#f8fafc] pl-3 pr-24 py-2.5 rounded-lg border border-[#1e305e] focus:outline-none focus:border-[#ff9933] placeholder:text-[#64748b]"
                />
                {enableMapsGrounding && (
                  <span className="absolute right-2.5 top-2 text-[10px] font-mono text-[#22c55e] bg-[#22c55e]/15 px-2 py-0.5 rounded border border-[#22c55e]/40 pointer-events-none">
                    MAPS ON
                  </span>
                )}
              </div>

              <button
                type="submit"
                disabled={isGenerating || !inputValue.trim()}
                className="px-4 py-2.5 rounded-lg bg-[#ff9933] hover:bg-[#e68a00] text-[#070d1e] font-bold font-mono text-xs transition-all disabled:opacity-40 flex items-center space-x-1.5 cursor-pointer shrink-0 shadow-md"
              >
                <span>SEND</span>
                <span className="material-symbols-outlined text-sm">send</span>
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
};
